# Generated by Django 4.2.7 on 2023-12-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('children', models.IntegerField()),
                ('smoker', models.IntegerField()),
            ],
        ),
    ]
